queue = []
print("Adding Elements")
queue.insert(0, 10)
print(queue)
queue.insert(0, 20)
print(queue)
queue.insert(0, 30)
print(queue)
queue.insert(0, 40)
print(queue)
queue.insert(0, 50)
print(queue)

print("\nRemoving Elements")
queue.pop()
print(queue)
queue.pop()
print(queue)
queue.pop()
print(queue)
queue.pop()
print(queue)
